### ISSUE TITLE
Not Recognizing Me As Admin

### ISSUE THREAD

**Issue by lightsourced** [JereKuusela/valheim-dev#1]
I am setup as an admin on my server, and I have the mod/config installed on both the server and client side. When I type devcommands into the console it says I don't have admin privileges. I even have my steamID in the Root Users string in the config. Not sure how to resolve this, thanks!

**Comment by JereKuusela** [comment]
This should be now fixed in the v1.14 version.

**Comment by lightsourced** [comment]
hmm.. still encountering the issue after updating.

**Comment by lightsourced** [comment]
Still encountering this issue. I'm using several other mods that require admin privileges and I'm not running into any issues with those. Keeps saying I'm not authorized to use devcommands. Is there something I need to change in the config?

**Comment by lightsourced** [comment]
I don't know what happened but it just decided to work! I'm going to close this now, sorry bothering you with this, may have just been a silly server thing, who knows.
